version: '2'

services:
  data-science:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "sleep 5 && jupyter notebook --ip=0.0.0.0 --allow-root"
    volumes:
      - .:/data-science
      - ./notebooks:/opt/notebooks
    ports:
      - '127.0.0.1:8888:8888'
    network_mode: "bridge"
volumes:
  notebooks: