version: '2'

services:
  web:
    build: .
    stdin_open: true
    tty: true
    # command: ["/bin/bash", "/app/wait-for-postgres.sh", "postgres", "/bin/bash", "/app/entrypoint.sh"]
    volumes:
      - .:/data-science
      - ./notebooks:/opt/notebooks
    ports:
      - '127.0.0.1:8888:8888'
    # links:
    #   - redis:redis
    #   - postgres:postgres
    network_mode: "bridge"
volumes:
  notebooks: